name: example
description: example
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-109.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  drag_and_drop_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
